# Generated by Django 2.2.17 on 2021-01-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=30)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
