# Generated by Django 2.2.17 on 2021-01-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='email',
            new_name='email2',
        ),
    ]
