# Generated by Django 2.2.17 on 2021-01-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20210130_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='email2',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
