# Generated by Django 2.2.17 on 2021-01-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20210130_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
