# Generated by Django 2.2.17 on 2021-01-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(default='', max_length=30)),
            ],
        ),
    ]
