# Generated by Django 2.2.17 on 2021-01-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_mail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
